In [6]:
!pip install pandas

Requirement already satisfied: pandas in e:\anconda\envs\jupyter_env\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in e:\anconda\envs\jupyter_env\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\anconda\envs\jupyter_env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in e:\anconda\envs\jupyter_env\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in e:\anconda\envs\jupyter_env\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in e:\anconda\envs\jupyter_env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
#import pandas
import pandas as pd

In [3]:
pd.__version__

'2.3.3'

In [9]:
#1. Create Dataframe
df = pd.DataFrame([1,2,3])
print(df)

   0
0  1
1  2
2  3

In [10]:
df = pd.DataFrame([11,22,33],columns=['Col_Name'])
print(df)

   Col_Name
0        11
1        22
2        33

In [11]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [12]:
data = {
    'Name': ['Madhav', 'Vishakha', 'Lalita', 'Ram'],
    'Age': [16,17,18,19],
    'Salary' : [90000, 70000, 50000, 30000] 
}

In [13]:
df = pd.DataFrame(data)
print(df)

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000
2    Lalita   18   50000
3       Ram   19   30000

In [14]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [15]:
#2. Basic Dataframe Understanding

In [16]:
df.head()   #top rowa

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000
2    Lalita   18   50000
3       Ram   19   30000

In [17]:
df.head(2)

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000

In [18]:
df.tail()   #last rows

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000
2    Lalita   18   50000
3       Ram   19   30000

In [19]:
df.tail(2)

     Name  Age  Salary
2  Lalita   18   50000
3     Ram   19   30000

In [20]:
df.shape

(4, 3)

In [21]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [22]:
#columns Rename
df.rename(columns={'Salary':'Monthly_Salary'})

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3       Ram   19           30000

In [23]:
df1=df.rename(columns={'Salary': 'Monthly_Salary'}, inplace=True)

In [24]:
df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3       Ram   19           30000

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      object
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes

In [26]:
df.describe()

             Age  Monthly_Salary
count   4.000000        4.000000
mean   17.500000    60000.000000
std     1.290994    25819.888975
min    16.000000    30000.000000
25%    16.750000    45000.000000
50%    17.500000    60000.000000
75%    18.250000    75000.000000
max    19.000000    90000.000000

In [27]:
#3. Save and Load data from csv

In [28]:
#export dataframe
df.to_csv('Test_data.csv')

In [29]:
df.to_csv('Test_data.csv',index=False)

In [30]:
#import dataframe
load_df = pd.read_csv('Test_data.csv')
load_df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3       Ram   19           30000

In [31]:
#4. Rows & Column - Selection

In [32]:
#select column
#single column
df[['Name']]

       Name
0    Madhav
1  Vishakha
2    Lalita
3       Ram

In [33]:
df[['Name', 'Monthly_Salary']]

       Name  Monthly_Salary
0    Madhav           90000
1  Vishakha           70000
2    Lalita           50000
3       Ram           30000

In [34]:
# Select Rows
#loc- index name label based
#df.loc[df.Name=='Madhav']    #Square Brackets:
df.loc[(df.Name=='Madhav') & (df.Monthly_Salary>=50000)]

     Name  Age  Monthly_Salary
0  Madhav   16           90000

In [35]:
#iloc - index-value based
df.iloc[0:]

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3       Ram   19           30000

In [36]:
df.iloc[0:2]   #[start:stop:step]

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000

In [37]:
#5. Dataframe filter

In [38]:
df_age_filter = df[df['Age']>=17]

In [39]:
df_age_filter

       Name  Age  Monthly_Salary
1  Vishakha   17           70000
2    Lalita   18           50000
3       Ram   19           30000

In [40]:
df[(df['Age'] >= 18) & (df['Monthly_Salary'] >= 50000)]

     Name  Age  Monthly_Salary
2  Lalita   18           50000

In [41]:
df.where(df['Age'] >= 18)

     Name   Age  Monthly_Salary
0     NaN   NaN             NaN
1     NaN   NaN             NaN
2  Lalita  18.0         50000.0
3     Ram  19.0         30000.0

In [42]:
df.where(df['Age'] >= 18, other = 'Not Elegible')

           Name           Age Monthly_Salary
0  Not Elegible  Not Elegible   Not Elegible
1  Not Elegible  Not Elegible   Not Elegible
2        Lalita            18          50000
3           Ram            19          30000

In [43]:
#6. Rows and Columns - Operation (Add,Update,Delete)

In [44]:
df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3       Ram   19           30000

In [45]:
# Add New column
df['Team'] = ['CEO','HR','CTO','DA']
df

       Name  Age  Monthly_Salary Team
0    Madhav   16           90000  CEO
1  Vishakha   17           70000   HR
2    Lalita   18           50000  CTO
3       Ram   19           30000   DA

In [46]:
df = df.drop_duplicates()
df

       Name  Age  Monthly_Salary Team
0    Madhav   16           90000  CEO
1  Vishakha   17           70000   HR
2    Lalita   18           50000  CTO
3       Ram   19           30000   DA

In [48]:
df['Bonus'] = df['Monthly_Salary'] * 0.2
df

       Name  Age  Monthly_Salary Team    Bonus
0    Madhav   16           90000  CEO  18000.0
1  Vishakha   17           70000   HR  14000.0
2    Lalita   18           50000  CTO  10000.0
3       Ram   19           30000   DA   6000.0

In [49]:
#ADD new rows
#df.loc[len(df)] = ['ABC', 21, 21000, 'IT',2000] 
df.loc[len(df)] = {
    'Name': 'ABC',
    'Age': 21,
    'Salary': 21000,
    'Team': 'IT',
    'Bonus': 2000
}
df

       Name  Age  Monthly_Salary Team    Bonus
0    Madhav   16         90000.0  CEO  18000.0
1  Vishakha   17         70000.0   HR  14000.0
2    Lalita   18         50000.0  CTO  10000.0
3       Ram   19         30000.0   DA   6000.0
4       ABC   21             NaN   IT   2000.0

In [50]:
len(df)

5

In [51]:
# Update Values
df.loc[0, 'Monthly_Salary'] = 95000
df

       Name  Age  Monthly_Salary Team    Bonus
0    Madhav   16         95000.0  CEO  18000.0
1  Vishakha   17         70000.0   HR  14000.0
2    Lalita   18         50000.0  CTO  10000.0
3       Ram   19         30000.0   DA   6000.0
4       ABC   21             NaN   IT   2000.0

In [52]:
# Update value - using column value
df.loc[df.Name == 'Madhav', 'Monthly_Salary'] = 90000
df

       Name  Age  Monthly_Salary Team    Bonus
0    Madhav   16         90000.0  CEO  18000.0
1  Vishakha   17         70000.0   HR  14000.0
2    Lalita   18         50000.0  CTO  10000.0
3       Ram   19         30000.0   DA   6000.0
4       ABC   21             NaN   IT   2000.0

In [53]:
# Delete Value - Rows and Columns Values

In [54]:
df.drop(df[df.Name == 'ABC'].index)   #drop row at axis=0

       Name  Age  Monthly_Salary Team    Bonus
0    Madhav   16         90000.0  CEO  18000.0
1  Vishakha   17         70000.0   HR  14000.0
2    Lalita   18         50000.0  CTO  10000.0
3       Ram   19         30000.0   DA   6000.0

In [ ]:
df.drop(5, axis=0)  #axis name

In [ ]:
df.drop(7, axis=0)  #axis name

In [ ]:
df[df.Name == 'ABC']

In [ ]:
df.rename(columns={'Monthly_Salary':'Salary'},inplace=True)

In [ ]:
# sort Values in Ascending order
df.sort_values('Salary')

In [ ]:
#Descending order
df.sort_values('Salary', ascending= False)

In [56]:
#7. Working with Date values

In [60]:
#create new column
df['DOJ'] = [
    '2026-01-15',
    '2025-02-06',
    '2026-01-14',
    '2026-01-15',
    '2025-02-06'
]
df

       Name  Age  Monthly_Salary Team    Bonus         DOJ
0    Madhav   16         90000.0  CEO  18000.0  2026-01-15
1  Vishakha   17         70000.0   HR  14000.0  2025-02-06
2    Lalita   18         50000.0  CTO  10000.0  2026-01-14
3       Ram   19         30000.0   DA   6000.0  2026-01-15
4       ABC   21             NaN   IT   2000.0  2025-02-06

In [61]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [62]:
print(df)
print(df['DOJ'].dtype)

       Name  Age  Monthly_Salary Team    Bonus        DOJ
0    Madhav   16         90000.0  CEO  18000.0 2026-01-15
1  Vishakha   17         70000.0   HR  14000.0 2025-02-06
2    Lalita   18         50000.0  CTO  10000.0 2026-01-14
3       Ram   19         30000.0   DA   6000.0 2026-01-15
4       ABC   21             NaN   IT   2000.0 2025-02-06
datetime64[ns]

In [64]:
df['DOJ'] = pd.to_datetime(df['DOJ'],format = '%d-%m-%Y')

In [65]:
df

       Name  Age  Monthly_Salary Team    Bonus        DOJ
0    Madhav   16         90000.0  CEO  18000.0 2026-01-15
1  Vishakha   17         70000.0   HR  14000.0 2025-02-06
2    Lalita   18         50000.0  CTO  10000.0 2026-01-14
3       Ram   19         30000.0   DA   6000.0 2026-01-15
4       ABC   21             NaN   IT   2000.0 2025-02-06

In [66]:
print(df['DOJ'].dtype)

datetime64[ns]

In [67]:
#Extract Year, Month, Week, Day
df['DOJ'].dt.year
df['DOJ'].dt.month
df['DOJ'].dt.day
df['DOJ'].dt.day_name()

0     Thursday
1     Thursday
2    Wednesday
3     Thursday
4     Thursday
Name: DOJ, dtype: object

In [68]:
df['Month'] = df['DOJ'].dt.month

In [69]:
df

       Name  Age  Monthly_Salary Team    Bonus        DOJ  Month
0    Madhav   16         90000.0  CEO  18000.0 2026-01-15      1
1  Vishakha   17         70000.0   HR  14000.0 2025-02-06      2
2    Lalita   18         50000.0  CTO  10000.0 2026-01-14      1
3       Ram   19         30000.0   DA   6000.0 2026-01-15      1
4       ABC   21             NaN   IT   2000.0 2025-02-06      2

In [71]:
df['DOJ'] + pd.Timedelta(days=90)

0   2026-04-15
1   2025-05-07
2   2026-04-14
3   2026-04-15
4   2025-05-07
Name: DOJ, dtype: datetime64[ns]

In [74]:
#8. Handling Missing Values

In [75]:
df

       Name  Age  Monthly_Salary Team    Bonus        DOJ  Month
0    Madhav   16         90000.0  CEO  18000.0 2026-01-15      1
1  Vishakha   17         70000.0   HR  14000.0 2025-02-06      2
2    Lalita   18         50000.0  CTO  10000.0 2026-01-14      1
3       Ram   19         30000.0   DA   6000.0 2026-01-15      1
4       ABC   21             NaN   IT   2000.0 2025-02-06      2

In [77]:
df.isnull()

    Name    Age  Monthly_Salary   Team  Bonus    DOJ  Month
0  False  False           False  False  False  False  False
1  False  False           False  False  False  False  False
2  False  False           False  False  False  False  False
3  False  False           False  False  False  False  False
4  False  False            True  False  False  False  False

In [78]:
import numpy as np

In [81]:
df.loc[df.Name=='Madhav', 'Monthly_Salary'] = np.nan

In [83]:
df

       Name  Age  Monthly_Salary Team    Bonus        DOJ  Month  Salary
0    Madhav   16             NaN  CEO  18000.0 2026-01-15      1     NaN
1  Vishakha   17         70000.0   HR  14000.0 2025-02-06      2     NaN
2    Lalita   18         50000.0  CTO  10000.0 2026-01-14      1     NaN
3       Ram   19         30000.0   DA   6000.0 2026-01-15      1     NaN
4       ABC   21             NaN   IT   2000.0 2025-02-06      2     NaN

In [84]:
df.isnull()

    Name    Age  Monthly_Salary   Team  Bonus    DOJ  Month  Salary
0  False  False            True  False  False  False  False    True
1  False  False           False  False  False  False  False    True
2  False  False           False  False  False  False  False    True
3  False  False           False  False  False  False  False    True
4  False  False            True  False  False  False  False    True

In [85]:
df.isnull().sum()

Name              0
Age               0
Monthly_Salary    2
Team              0
Bonus             0
DOJ               0
Month             0
Salary            5
dtype: int64

In [86]:
df.fillna(50000)

       Name  Age  Monthly_Salary Team    Bonus        DOJ  Month   Salary
0    Madhav   16         50000.0  CEO  18000.0 2026-01-15      1  50000.0
1  Vishakha   17         70000.0   HR  14000.0 2025-02-06      2  50000.0
2    Lalita   18         50000.0  CTO  10000.0 2026-01-14      1  50000.0
3       Ram   19         30000.0   DA   6000.0 2026-01-15      1  50000.0
4       ABC   21         50000.0   IT   2000.0 2025-02-06      2  50000.0

In [91]:
#9. Aggregation and Group By

#To Know Total values (Frequency)

In [92]:
df['Team'].value_counts()

Team
CEO    1
HR     1
CTO    1
DA     1
IT     1
Name: count, dtype: int64

In [93]:
df['Month'].value_counts()

Month
1    3
2    2
Name: count, dtype: int64

In [105]:
df[df['Month'] == 1]

     Name  Age  Monthly_Salary Team    Bonus        DOJ  Month  Salary
0  Madhav   16             NaN  CEO  18000.0 2026-01-15      1     NaN
2  Lalita   18         50000.0  CTO  10000.0 2026-01-14      1     NaN
3     Ram   19         30000.0   DA   6000.0 2026-01-15      1     NaN

In [106]:
df[df['Month'] == 1].shape[0]

3

In [109]:
df.groupby('Month')['Monthly_Salary'].sum()  # Aggregation bassed on group by

Month
1    80000.0
2    70000.0
Name: Monthly_Salary, dtype: float64

In [110]:
df.groupby('Month').agg({'Monthly_Salary' : 'mean', 'Name' : 'count'})

       Monthly_Salary  Name
Month
1             40000.0     3
2             70000.0     2

In [111]:
#10. Concatenating and Merge Dataframe (JOINS)

In [112]:
df1 = pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [113]:
df2 = pd.DataFrame({'ID':[1,2,2,4],'Score':[88,96,77,79]})
df2

   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

In [115]:
#Verticle / Row-Level / Top on Top 
pd.concat([df1,df2],axis=0)

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [117]:
# Horizontal / Column Level / Side on Side
pd.concat([df1,df2], axis=1)

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   2     77
3  NaN  NaN   4     79

In [118]:
#Merge=Join

In [119]:
pd.merge(df1, df2, how='inner', on='ID')

'''pd.merge(df1, df2, how='left', on='ID')
pd.merge(df1, df2, how='right', on='ID')
pd.merge(df1, df2, how='outer', on='ID')'''

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [120]:
pd.merge(df1, df2, how='inner', left_on='ID', right_on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [121]:
#11. AI and ChatGPT

In [122]:
df

       Name  Age  Monthly_Salary Team    Bonus        DOJ  Month  Salary
0    Madhav   16             NaN  CEO  18000.0 2026-01-15      1     NaN
1  Vishakha   17         70000.0   HR  14000.0 2025-02-06      2     NaN
2    Lalita   18         50000.0  CTO  10000.0 2026-01-14      1     NaN
3       Ram   19         30000.0   DA   6000.0 2026-01-15      1     NaN
4       ABC   21             NaN   IT   2000.0 2025-02-06      2     NaN